import type { RoomDefinition } from "@/house/engine/types";

export const rooms = {
  hall: {
    id: "hall",
    name: "The Great Hall",
    image: "/rooms/hall-001.JPG",
    description: "The central threshold of the House.",
    cameraStart: { zoom: 1, panX: 0, panY: 0 },
    atmosphere: { vignette: "heavy", particles: "gold-dust" },
    preloadNext: ["/rooms/charter-001.JPG", "/rooms/music-001.JPG"],
    hotspots: [
      {
        id: "charter-door",
        type: "seal",
        label: "Charter Chamber",
        x: 14,
        y: 67,
        width: 20,
        height: 24,
        route: "/house/charter",
        camera: { zoom: 1.22, panX: 8, panY: -2 },
      },
      {
        id: "music-stair",
        type: "staircase",
        label: "Music Chamber",
        x: 61,
        y: 58,
        width: 25,
        height: 28,
        route: "/house/music",
        camera: { zoom: 1.3, panX: -8, panY: -9 },
      },
      {
        id: "vision-frame",
        type: "projector",
        label: "Vision Observatory",
        x: 41,
        y: 32,
        width: 18,
        height: 24,
        route: "/house/vision",
        camera: { zoom: 1.55, panX: 0, panY: -18 },
      },
    ],
  },
  charter: {
    id: "charter",
    name: "Charter Chamber",
    image: "/rooms/charter-001.JPG",
    description: "A chamber of articles, symbols, and founding vows.",
    cameraStart: { zoom: 1.04, panX: 0, panY: 0 },
    atmosphere: { vignette: "heavy", particles: "haze" },
    preloadNext: ["/rooms/hall-001.JPG", "/rooms/vision-001.JPG"],
    hotspots: [
      {
        id: "return-hall",
        type: "door",
        label: "Return to Hall",
        x: 38,
        y: 76,
        width: 24,
        height: 16,
        route: "/house/hall",
        camera: { zoom: 1.22, panX: 0, panY: 9 },
      },
      {
        id: "article-three",
        type: "seal",
        label: "Article III",
        x: 39,
        y: 35,
        width: 23,
        height: 27,
        action: "inspect",
        camera: { zoom: 1.48, panX: 0, panY: -10 },
      },
    ],
  },
  music: {
    id: "music",
    name: "Music Chamber",
    image: "/rooms/music-001.JPG",
    description: "A working chamber for sound, score, and signal.",
    cameraStart: { zoom: 1.02, panX: 0, panY: 0 },
    atmosphere: { vignette: "soft", particles: "starlight" },
    preloadNext: ["/rooms/hall-001.JPG", "/rooms/vision-001.JPG"],
    hotspots: [
      {
        id: "return-hall",
        type: "door",
        label: "Return to Hall",
        x: 5,
        y: 62,
        width: 18,
        height: 23,
        route: "/house/hall",
        camera: { zoom: 1.18, panX: 10, panY: 2 },
      },
      {
        id: "main-console",
        type: "speaker",
        label: "Main Console",
        x: 24,
        y: 67,
        width: 58,
        height: 18,
        action: "inspect",
        camera: { zoom: 1.35, panX: 0, panY: 14 },
      },
    ],
  },
  vision: {
    id: "vision",
    name: "Vision Observatory",
    image: "/rooms/vision-001.JPG",
    description: "A projection room for cinema, image, and future works.",
    cameraStart: { zoom: 1, panX: 0, panY: 0 },
    atmosphere: { vignette: "soft", particles: "starlight" },
    preloadNext: ["/rooms/hall-001.JPG", "/rooms/music-001.JPG"],
    hotspots: [
      {
        id: "return-hall",
        type: "door",
        label: "Return to Hall",
        x: 39,
        y: 78,
        width: 24,
        height: 14,
        route: "/house/hall",
        camera: { zoom: 1.18, panX: 0, panY: 12 },
      },
      {
        id: "dome",
        type: "projector",
        label: "Projection Dome",
        x: 12,
        y: 4,
        width: 76,
        height: 50,
        action: "inspect",
        camera: { zoom: 1.38, panX: 0, panY: -20 },
      },
    ],
  },
} satisfies Record<string, RoomDefinition>;

export const roomIds = Object.keys(rooms);

export function getRoom(id: string) {
  return rooms[id as keyof typeof rooms];
}
